<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <RootNamespace>func_pdf_generator</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="jsreport.Local" Version="2.2.2" />
    <PackageReference Include="jsreport.Binary" Version="2.7.1" />
    <PackageReference Include="jsreport.Types" Version="2.7.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.6.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="jsreport\data\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
